# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from geotagger/MavrosData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class MavrosData(genpy.Message):
  _md5sum = "504b4cf00b55003d0350cb2c79a82ffc"
  _type = "geotagger/MavrosData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# geotagger/MavrosData.msg

#include "std_msgs/Header.msg"


float64 latitude
float64 longitude
float64 altitude
float64 compass_heading
float64 yaw
time timestamp
"""
  __slots__ = ['latitude','longitude','altitude','compass_heading','yaw','timestamp']
  _slot_types = ['float64','float64','float64','float64','float64','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,altitude,compass_heading,yaw,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MavrosData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.compass_heading is None:
        self.compass_heading = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.timestamp is None:
        self.timestamp = genpy.Time()
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.compass_heading = 0.
      self.yaw = 0.
      self.timestamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d2I().pack(_x.latitude, _x.longitude, _x.altitude, _x.compass_heading, _x.yaw, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.latitude, _x.longitude, _x.altitude, _x.compass_heading, _x.yaw, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_5d2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d2I().pack(_x.latitude, _x.longitude, _x.altitude, _x.compass_heading, _x.yaw, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.latitude, _x.longitude, _x.altitude, _x.compass_heading, _x.yaw, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_5d2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d2I = None
def _get_struct_5d2I():
    global _struct_5d2I
    if _struct_5d2I is None:
        _struct_5d2I = struct.Struct("<5d2I")
    return _struct_5d2I
